import type { Metadata } from "next"; // ページ全体のメタ情報を型で管理
import { Geist, Geist_Mono } from "next/font/google"; // Google Fonts（Geist）の読み込み
import "./globals.css"; // Tailwindや共通スタイルを適用
import Header from "@/components/Header"; // ヘッダーコンポーネントの読み込み

// フォントの設定（カスタムプロパティとして利用）
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// サイト全体のメタデータ（SEOやOGPにも影響する）
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// ルートレイアウト：全ページで共通となるHTML構造を定義
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode; // 子コンテンツ（各ページ）がここに挿入される
}>) {
  return (
    <html lang="ja">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header /> {/* ← 全ページ共通のナビゲーションバー */}
        <main className="min-h-screen">{children}</main> {/* ページ固有の内容 */}
      </body>
    </html>
  );
}